//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.2
//     from Assets/Scripts/InputSystem/InputSystem_CoreActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @InputSystem_CoreActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystem_CoreActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem_CoreActions"",
    ""maps"": [
        {
            ""name"": ""Hotkeys"",
            ""id"": ""57248ef9-7756-4879-a5d6-96ecac365c76"",
            ""actions"": [
                {
                    ""name"": ""GameSpeed_Normal"",
                    ""type"": ""Button"",
                    ""id"": ""0cb5b75d-ca91-4057-8396-24dbb925c599"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GameSpeed_Double"",
                    ""type"": ""Button"",
                    ""id"": ""dae1dc30-8d4e-45af-9077-4b13e670072b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GameSpeed_Triple"",
                    ""type"": ""Button"",
                    ""id"": ""47a00c93-be6f-4202-9d09-570454cab53a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GamePause"",
                    ""type"": ""Button"",
                    ""id"": ""edf59c91-6c18-4494-a587-e7e4ee67e1d7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Building"",
                    ""type"": ""Button"",
                    ""id"": ""04cd2145-3e1b-4371-b76a-19d9775ae47c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""d473a591-ab87-4e73-8f8f-dcaed398378f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""d6ac652c-65e3-4cb3-bb05-2ef5642b80b2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a31eb972-c354-4fdc-b95e-02466f381ab1"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GameSpeed_Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d942a91b-ce8a-4e83-93d9-bda8b9031c49"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GameSpeed_Double"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef066c39-6567-40c3-a84b-b18253b69737"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GameSpeed_Triple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9fa20d5-c08f-4565-b929-ab8bac36d4d2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GamePause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab74e5eb-068f-45f0-8e63-ea26c68bdace"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Building"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d169982-2ab7-4c3f-964a-1bf0e154ad38"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07fe7eee-1da5-444d-b6c8-9024498871c2"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Hotkeys
        m_Hotkeys = asset.FindActionMap("Hotkeys", throwIfNotFound: true);
        m_Hotkeys_GameSpeed_Normal = m_Hotkeys.FindAction("GameSpeed_Normal", throwIfNotFound: true);
        m_Hotkeys_GameSpeed_Double = m_Hotkeys.FindAction("GameSpeed_Double", throwIfNotFound: true);
        m_Hotkeys_GameSpeed_Triple = m_Hotkeys.FindAction("GameSpeed_Triple", throwIfNotFound: true);
        m_Hotkeys_GamePause = m_Hotkeys.FindAction("GamePause", throwIfNotFound: true);
        m_Hotkeys_Building = m_Hotkeys.FindAction("Building", throwIfNotFound: true);
        m_Hotkeys_Escape = m_Hotkeys.FindAction("Escape", throwIfNotFound: true);
        m_Hotkeys_LeftMouseButton = m_Hotkeys.FindAction("LeftMouseButton", throwIfNotFound: true);
    }

    ~@InputSystem_CoreActions()
    {
        Debug.Assert(!m_Hotkeys.enabled, "This will cause a leak and performance issues, InputSystem_CoreActions.Hotkeys.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Hotkeys
    private readonly InputActionMap m_Hotkeys;
    private List<IHotkeysActions> m_HotkeysActionsCallbackInterfaces = new List<IHotkeysActions>();
    private readonly InputAction m_Hotkeys_GameSpeed_Normal;
    private readonly InputAction m_Hotkeys_GameSpeed_Double;
    private readonly InputAction m_Hotkeys_GameSpeed_Triple;
    private readonly InputAction m_Hotkeys_GamePause;
    private readonly InputAction m_Hotkeys_Building;
    private readonly InputAction m_Hotkeys_Escape;
    private readonly InputAction m_Hotkeys_LeftMouseButton;
    public struct HotkeysActions
    {
        private @InputSystem_CoreActions m_Wrapper;
        public HotkeysActions(@InputSystem_CoreActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @GameSpeed_Normal => m_Wrapper.m_Hotkeys_GameSpeed_Normal;
        public InputAction @GameSpeed_Double => m_Wrapper.m_Hotkeys_GameSpeed_Double;
        public InputAction @GameSpeed_Triple => m_Wrapper.m_Hotkeys_GameSpeed_Triple;
        public InputAction @GamePause => m_Wrapper.m_Hotkeys_GamePause;
        public InputAction @Building => m_Wrapper.m_Hotkeys_Building;
        public InputAction @Escape => m_Wrapper.m_Hotkeys_Escape;
        public InputAction @LeftMouseButton => m_Wrapper.m_Hotkeys_LeftMouseButton;
        public InputActionMap Get() { return m_Wrapper.m_Hotkeys; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HotkeysActions set) { return set.Get(); }
        public void AddCallbacks(IHotkeysActions instance)
        {
            if (instance == null || m_Wrapper.m_HotkeysActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HotkeysActionsCallbackInterfaces.Add(instance);
            @GameSpeed_Normal.started += instance.OnGameSpeed_Normal;
            @GameSpeed_Normal.performed += instance.OnGameSpeed_Normal;
            @GameSpeed_Normal.canceled += instance.OnGameSpeed_Normal;
            @GameSpeed_Double.started += instance.OnGameSpeed_Double;
            @GameSpeed_Double.performed += instance.OnGameSpeed_Double;
            @GameSpeed_Double.canceled += instance.OnGameSpeed_Double;
            @GameSpeed_Triple.started += instance.OnGameSpeed_Triple;
            @GameSpeed_Triple.performed += instance.OnGameSpeed_Triple;
            @GameSpeed_Triple.canceled += instance.OnGameSpeed_Triple;
            @GamePause.started += instance.OnGamePause;
            @GamePause.performed += instance.OnGamePause;
            @GamePause.canceled += instance.OnGamePause;
            @Building.started += instance.OnBuilding;
            @Building.performed += instance.OnBuilding;
            @Building.canceled += instance.OnBuilding;
            @Escape.started += instance.OnEscape;
            @Escape.performed += instance.OnEscape;
            @Escape.canceled += instance.OnEscape;
            @LeftMouseButton.started += instance.OnLeftMouseButton;
            @LeftMouseButton.performed += instance.OnLeftMouseButton;
            @LeftMouseButton.canceled += instance.OnLeftMouseButton;
        }

        private void UnregisterCallbacks(IHotkeysActions instance)
        {
            @GameSpeed_Normal.started -= instance.OnGameSpeed_Normal;
            @GameSpeed_Normal.performed -= instance.OnGameSpeed_Normal;
            @GameSpeed_Normal.canceled -= instance.OnGameSpeed_Normal;
            @GameSpeed_Double.started -= instance.OnGameSpeed_Double;
            @GameSpeed_Double.performed -= instance.OnGameSpeed_Double;
            @GameSpeed_Double.canceled -= instance.OnGameSpeed_Double;
            @GameSpeed_Triple.started -= instance.OnGameSpeed_Triple;
            @GameSpeed_Triple.performed -= instance.OnGameSpeed_Triple;
            @GameSpeed_Triple.canceled -= instance.OnGameSpeed_Triple;
            @GamePause.started -= instance.OnGamePause;
            @GamePause.performed -= instance.OnGamePause;
            @GamePause.canceled -= instance.OnGamePause;
            @Building.started -= instance.OnBuilding;
            @Building.performed -= instance.OnBuilding;
            @Building.canceled -= instance.OnBuilding;
            @Escape.started -= instance.OnEscape;
            @Escape.performed -= instance.OnEscape;
            @Escape.canceled -= instance.OnEscape;
            @LeftMouseButton.started -= instance.OnLeftMouseButton;
            @LeftMouseButton.performed -= instance.OnLeftMouseButton;
            @LeftMouseButton.canceled -= instance.OnLeftMouseButton;
        }

        public void RemoveCallbacks(IHotkeysActions instance)
        {
            if (m_Wrapper.m_HotkeysActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHotkeysActions instance)
        {
            foreach (var item in m_Wrapper.m_HotkeysActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HotkeysActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HotkeysActions @Hotkeys => new HotkeysActions(this);
    public interface IHotkeysActions
    {
        void OnGameSpeed_Normal(InputAction.CallbackContext context);
        void OnGameSpeed_Double(InputAction.CallbackContext context);
        void OnGameSpeed_Triple(InputAction.CallbackContext context);
        void OnGamePause(InputAction.CallbackContext context);
        void OnBuilding(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
        void OnLeftMouseButton(InputAction.CallbackContext context);
    }
}
